-- Seed clubs des 5 grands championnats
-- La colonne "pays" sert de groupe de championnat ici

INSERT INTO equipe (nom, pays) VALUES
-- Ligue 1
('Paris Saint-Germain', 'Ligue 1'),
('Olympique de Marseille', 'Ligue 1'),
('Olympique Lyonnais', 'Ligue 1'),
('AS Monaco', 'Ligue 1'),
('OGC Nice', 'Ligue 1'),
('Lille OSC', 'Ligue 1'),
('Stade Rennais', 'Ligue 1'),
('RC Lens', 'Ligue 1'),
('Stade de Reims', 'Ligue 1'),
('RC Strasbourg', 'Ligue 1'),
('Montpellier HSC', 'Ligue 1'),
('FC Nantes', 'Ligue 1'),
('Toulouse FC', 'Ligue 1'),
('Girondins de Bordeaux', 'Ligue 1'),
('Stade Brestois', 'Ligue 1'),
('Angers SCO', 'Ligue 1'),
('Havre AC', 'Ligue 1'),
('Saint-Etienne', 'Ligue 1'),

-- Premier League
('Manchester City', 'Premier League'),
('Arsenal', 'Premier League'),
('Liverpool', 'Premier League'),
('Chelsea', 'Premier League'),
('Manchester United', 'Premier League'),
('Tottenham Hotspur', 'Premier League'),
('Newcastle United', 'Premier League'),
('Aston Villa', 'Premier League'),
('Brighton', 'Premier League'),
('West Ham United', 'Premier League'),
('Wolverhampton', 'Premier League'),
('Everton', 'Premier League'),
('Fulham', 'Premier League'),
('Brentford', 'Premier League'),
('Crystal Palace', 'Premier League'),
('Nottingham Forest', 'Premier League'),
('Leicester City', 'Premier League'),
('Leeds United', 'Premier League'),
('Southampton', 'Premier League'),
('Ipswich Town', 'Premier League'),

-- La Liga
('Real Madrid', 'La Liga'),
('FC Barcelone', 'La Liga'),
('Atletico Madrid', 'La Liga'),
('Real Sociedad', 'La Liga'),
('Athletic Bilbao', 'La Liga'),
('Villarreal', 'La Liga'),
('Real Betis', 'La Liga'),
('Valencia CF', 'La Liga'),
('Sevilla FC', 'La Liga'),
('Osasuna', 'La Liga'),
('Celta Vigo', 'La Liga'),
('Getafe CF', 'La Liga'),
('Rayo Vallecano', 'La Liga'),
('Girona FC', 'La Liga'),
('UD Las Palmas', 'La Liga'),
('Deportivo Alaves', 'La Liga'),
('RCD Mallorca', 'La Liga'),
('Leganes', 'La Liga'),

-- Serie A
('Inter Milan', 'Serie A'),
('AC Milan', 'Serie A'),
('Juventus', 'Serie A'),
('AS Roma', 'Serie A'),
('SS Lazio', 'Serie A'),
('Napoli', 'Serie A'),
('Atalanta', 'Serie A'),
('Fiorentina', 'Serie A'),
('Bologna', 'Serie A'),
('Torino', 'Serie A'),
('Udinese', 'Serie A'),
('Sassuolo', 'Serie A'),
('Sampdoria', 'Serie A'),
('Hellas Verona', 'Serie A'),
('Genoa', 'Serie A'),
('Cagliari', 'Serie A'),
('Empoli', 'Serie A'),
('Monza', 'Serie A'),

-- Bundesliga
('Bayern Munich', 'Bundesliga'),
('Borussia Dortmund', 'Bundesliga'),
('RB Leipzig', 'Bundesliga'),
('Bayer Leverkusen', 'Bundesliga'),
('Eintracht Francfort', 'Bundesliga'),
('SC Freiburg', 'Bundesliga'),
('Union Berlin', 'Bundesliga'),
('Borussia Monchengladbach', 'Bundesliga'),
('Wolfsburg', 'Bundesliga'),
('Hoffenheim', 'Bundesliga'),
('Mainz 05', 'Bundesliga'),
('Werder Breme', 'Bundesliga'),
('Augsburg', 'Bundesliga'),
('Stuttgart', 'Bundesliga'),
('Cologne', 'Bundesliga'),
('Hertha Berlin', 'Bundesliga'),
('Schalke 04', 'Bundesliga'),
('Hamburger SV', 'Bundesliga')

ON CONFLICT (nom, pays) DO NOTHING;
