INSERT INTO EQUIPE (Nom, Pays, ID_API) VALUES
  ('Irlande du Nord', 'Royaume-Uni',  'nat-nireland'),
  ('Etats-Unis',      'USA',          'nat-usa'),
  ('Mexique',         'Mexique',      'nat-mexico'),
  ('Canada',          'Canada',       'nat-canada'),
  ('Argentine',       'Argentine',    'nat-argentina'),
  ('Bresil',          'Bresil',       'nat-brazil'),
  ('Espagne',         'Espagne',      'nat-spain'),
  ('Allemagne',       'Allemagne',    'nat-germany'),
  ('Angleterre',      'Angleterre',   'nat-england'),
  ('Portugal',        'Portugal',     'nat-portugal'),
  ('Maroc',           'Maroc',        'nat-morocco'),
  ('Belgique',        'Belgique',     'nat-belgium'),
  ('Pays-Bas',        'Pays-Bas',     'nat-netherlands'),
  ('Uruguay',         'Uruguay',      'nat-uruguay'),
  ('Bolivie',         'Bolivie',      'nat-bolivia'),
  ('Jamaique',        'Jamaique',     'nat-jamaica'),
  ('Honduras',        'Honduras',     'nat-honduras'),
  ('Panama',          'Panama',       'nat-panama'),
  ('Australie',       'Australie',    'nat-australia'),
  ('Japon',           'Japon',        'nat-japan'),
  ('Coree du Sud',    'Coree du Sud', 'nat-southkorea'),
  ('Senegal',         'Senegal',      'nat-senegal'),
  ('Colombie',        'Colombie',     'nat-colombia'),
  ('Equateur',        'Equateur',     'nat-ecuador'),
  ('Suisse',          'Suisse',       'nat-switzerland'),
  ('Croatie',         'Croatie',      'nat-croatia'),
  ('Pologne',         'Pologne',      'nat-poland')
ON CONFLICT (Nom, Pays) DO NOTHING;
